### PR TITLE
Improve packaging and set up the CI

### LINKED ISSUE #1: Declare the dependencies
Now that we have our hands untied after the `pydensecrf` package has been updated on conda-forge, I would suggest if possible:

1. declaring the dependencies on which `doodler_engine` rely, by listing them in the setup.py file. I think it'd be possible to declare them instead in the setup.cfg file or in the pyproject.toml file, Python Packaging is evolving and being standardized, but I think you should be fine with listing them in the setup.py. If you are aware of some pins (for example this sort of pin numpy>1.5, <=.1.7), 
2. When 1. is done, make a release on PyPi
3.  When 2. is done, create a conda-forge recipe, this is usually pretty straightforward and I can help with that
4. When 3. is done, both dash-doodler and holodoodler can update their environments.yml to declare their dependency of `doodler_engine`

Given that dash-doodler and holodoodler are more of the application type of software vs. the library type, it'd be worth using `anaconda-project` to record:

* how to launch the application, e.g. with holodoodler that would be recording `panel serve app.py --show`
* an exact list of dependencies that are known to be working together. We call that creating a lock file and this is achieved with `anaconda-project lock`. When you tell your users to create their environment with `anaconda-project prepare`, if the lock file exists they will get the exact versions declared in the lock file, be it tomorrow or in a few years, which helps with making your work reproducible, and is good practice when you're managing an application.

### PR DESCRIPTION
**Pull request by maximlt**
Fixes https://github.com/Doodleverse/doodler_engine/issues/1

Hi @dbuscombe-usgs, this PR:

- adds a generic .gitignore file
- moves the project to using the relatively newer `pyproject.toml` file format that is now fully supported by `setuptools`. Since this is a new and simple package I thought that was a good opportunity.
- swaps `versioneer` for `setuptools-git-versioning`. I found `versioneer` a pain to set up and didn't like much to see it was adding files to the repo. Apparently `setuptools-git-versioning` doesn't and seemed to work seamlessly. This is by the way what Bokeh uses. As with `versioneer` - I believe - the package version is taken from git tag (e.g. `0.0.1`).
- The runtime dependencies and dev dependencies are declared in two `requirements.txt` files that are referenced in the `pyproject.toml` file. This allows installing the dependencies from conda with `conda install --file requirements.txt` which is quite handy in this case as we really want to use conda as I believe it's the way you recommend users to install the package. And `pydensecrf` is a pain to install. Note that `conda install --file requirements.txt` works under the condition that the packages doodler_engine depend on have the same name both on PyPI and conda-forge, which is the case for the current set of dependencies. If that were no longer to be true, you'd probably just declare the PyPI dependencies directly in the `pyprojec.toml` file and you would maintain a separate `environment.yml` file with the right conda names. In the HoloViz group we use an internal tool called pyctdev that deals with this sort of thing but we don't recommend anyone else using it, it's really tailored to our workflow and is a bit of a pain to deal with.
- sets up testing with `pytest` and a dummy test example, feel free to add as many tests as you want :)
- sets up CI to run the tests on every pull request and commit to the main branche
- sets up CI to build a source distribution and a wheel (with the `build` module) and deploys it to PyPI, this happens whenever you push a tag (e.g. `0.0.1`) to the repo, I've added some notes in the README

What is up to you now is to follow the instructions provided at the end of [this section](https://github.com/pypa/gh-action-pypi-publish#usage) to create an API Token and add it as to your repository secrets. If getting the token is too much of a pain (I've never done it), you could instead setup your PyPI username and password as secrets and update the last step of the build workflow accordingly.

EDIT: I forgot mentioning the most important part, compared to before the package now has runtime dependencies (`requirements.txt`). I explored the code base and added then whenever I saw an import referencing an external package. The pins come from the environment.yml file referenced in Doodler. I also setup the minimum Python version to be 3.8. It seems that it's what you recommend on Doodler now and 3.6 is "old" in the scientific Python ecosystem.

### CODE REVIEW

**Comment by ddbuscombe** [comment]
Thanks @maximlt ! Make sense (I think!) - I'm slammed until Thurs, but I will for sure try this out then and report back. More soon....

**Comment by 2320sharon** [comment]
Thank you for setting up things to make the doodler_engine an official package. I appreciate the template for automatically building the PyPI package since we have a few packages in the works currently. Do you recommend setting the `build` workflow set to run on `push` to a particular branch? @maximlt

**Comment by ddbuscombe** [comment]
I looked at the files of this PR. I guess the only question I have at the moment is the `requirements.txt`, which lists a bunch of dependencies. I thought that there were a lot of advantages to declare _zero_ dependencies, for the doodler-engine, because downstream applications (currently, DashDoodler and HoloDoodler and others in progress) work with their own respective conda environments. Sorry if I miscommunicated this before. Re-reading your original issue https://github.com/Doodleverse/doodler_engine/issues/1 , I guess I thought you would be creating updating separate packaging and CI for DashDoodler and HoloDoodler

I guess that this current PR is a necessary first-step, but the `requirements.txt` seems like it should still be blank. I really appreciate your taking the effort to do this @maximlt !

**Comment by maximlt** [comment]
> Do you recommend setting the build workflow set to run on push to a particular branch?

Not particularly no. There are certain scenarios - rare usually - where you want to build a new version from a branch. Say you're between v1 and v2, at v1.5 and decided your next version would be v2. You're adding features but someone reports a critical bug in v1.5, except it's too early to release v2. You can then create a branch off v1.5, patch it and release v.1.5.1 from that non-main branch.

> I thought that there were a lot of advantages to declare zero dependencies, for the doodler-engine, because downstream applications (currently, DashDoodler and HoloDoodler and others in progress) work with their own respective conda environments. Sorry if I miscommunicated this before.

Listing the dependencies of doodler_engine was all I meant to do really, everything else was optional and to make releasing easier :) The plan I have in mind is the following:
1. list the dependencies in doodler_engine: done in this PR
2. release doodler_engine on PyPI: I have no control over that
3. release doodler_engine on conda-forge: I can set up the recipe and add you as a maintainer for you to take care of the next ones
4. add doodler_engine as a dependency to the downstream applications: I'll take care of updating HoloDoodler

doodler_engine is meant to be a library depended upon by other libraries/applications. As such it should declare the dependencies it needs, other wise other libraries/applications would have to find out by themselves what dependencies it needs, what versions it supports, etc. This is what I've done in this PR :) Usually the standard practice is to pin the minimum version of the libraries you depend on (e.g. numpy>=1.x).

There's a difference between libraries (python packages) and applications (like HoloDoodler). Applications should pin exactly all their dependencies (e.g. numpy==1.5.0) so that they don't break when a new version (e.g. numpy 2) is released. Without pinning (we also say locking) them all, there's 100% chance sooner or later the application will break 🙃 So the role of a library developer is slightly different from the role of an application developer. As a library developer you want your library to be able to be used in many different environment configurations (e.g. different Python versions), you've got to test them the best you can. When a library you depend on (e.g. numpy) releases a breaking change to your library you either have to adapt it so that it works with the old and new version, or pin the offending dependency to the newest version. As an application developer you work in a context with fixed dependency, yet you have to make the effort to update your dependencies "regularly" as the libraries you depend on can get deprecated, it also avoids build up too much technical debt.

**Comment by ddbuscombe** [comment]
@maximlt thanks for the detailed explanation. I do understand what you are saying, however it is still not clear to me what advantage listing the doodler-engine dependencies are, if all we need to do is pip-install it into a conda environment that has its dependencies locked. I thought the lack of dependencies was the main feature, and I continue to think that. `doodler-engine` itself, not technically but in practice, has no dependencies outside of those already listed in the conda environments of the downstream applications. Otherwise, aren't we simply listing dependencies twice?

As for your plan to set up the conda recipe HoloDoodler, that would be greatly appreciated, thank you

**Comment by ddbuscombe** [comment]
Also please note that, for dash-doodler, we abandoned python 3.6 a while ago, in favour of a recipe listed [here](https://github.com/Doodleverse/dash_doodler#%EF%B8%8F-installation) on the README that works more reliably. We tested this on a number of platforms and conda installs, so we should probably remove the yml file now. Its a hangup from the bad days before you helped us get the `pydensecrf` conda-forge package and has been left merely as a fallback. But, as I say, we should probably now remove it

**Comment by ddbuscombe** [comment]
I chatted with @2320sharon about this, and based on our discussion I wanted to clarify a couple of things here to help with the confusion

1. `doodler-engine` purposefully has no dependencies because, currently, pip installs the code into an existing conda env. It literally just copies the functions into an environment that has already been established with the requisite dependencies. Its quite elegant because it means that we are relying solely on conda to provide a solution for downstream applications HoloDoodler and DashDoodler, not pip, and codes from `doodler-engine` do not need to be duplicated. It does mean, however, that the onus is on the downstream applications to maintain current API calls to existing dependencies 
2. I understand that individual dependencies can change in the future, which is why we are pursuing a locked version of the conda environments. If we lock in the current dependencies, then as far as I can tell, the current versions of `doodler-engine` codes need not change.
3. I understand that it means the downstream applications are beholden to the locked versions of libraries, as specified by the locked conda environments
4. If we lock the conda environments of the two downstream applications, the only reasons why I can think of for declaring the dependencies are as follows:
a. to document the versions of dependencies that we used for completeness/posterity. That is most efficiently taken care of in the README or a requirements.txt that is not actually used to install anything into the conda env
b. if conda REQUIRES you to create a requirements.txt file in `doodler-engine` to create the locked conda env (I cant see how this could be true, if you dont declare any dependencies, it won't know, right?)

So, it makes perfect sense (or at least I thought it did) for `holodoodler` and `dash-doodler` to have toml files, CI, tests, and lists of dependencies. It also makes sense to lock the conda environments of those applications. 

The old 'yml' file in dash-doodler references python 3.6 is no longer used since the pydensecrf library was added to conda forge, as I explain [here](https://github.com/Doodleverse/dash_doodler/issues/50). In the light (or dark :grin: ) of the above, does it still make sense to make this PR as-is? I guess I'm worried about declaring the requirements twice, once here, and again in each conda environment. It makes me question what the purpose of the locked conda environment is at all. Thanks again for your help on this, apologies if I am completely not getting it. It is my memory that we moved the `doodler-engine` to pip exactly to avoid having to declare dependencies twice, and it has worked well so far. My expectation was to lock the conda environments and this would be a done-deal.

**Comment by maximlt** [comment]
Just to make something clear because I'm not sure it is, the `requirements.txt` file in this repository is used to declare the dependencies of `doodler_engine`:

https://github.com/Doodleverse/doodler_engine/blob/9be510b34aa355d6d4de1d68ae10b9dcdf381067/pyproject.toml#L26-L27

If you `pip install` doodler_engine from this branch in an empty environment, you will see it is downloading the dependencies listed (and their transitive dependencies), it will most likely fail installing pydensecrf.

It is important for a library to declare programmatically its dependencies, as done above. If not, that opens the doors to many issues. For instance, you may build in the future another tool that depends on `doodler_engine`, that new tool being used in other applications. Without declaring the dependencies as I suggest, you will have to repeat them in the tool and the applications, or have the application maintainers track down the dependencies down to a README in this repo. Another scenario where this isn't optimal is the following. You release doodler_engine v2 with a bug fix and one dependency bumped, and then v3 with a new feature and at the same time you drop support for Python 3.8. Later someone may want to update HoloDoodler to get the bug fix but decides not to upgrade Python as it's a bigger undertaking. They'll try to install v2 and will have to check for themselves if some dependencies were changed/added/removed in v2, while the main branch of the repo will be more advanced and after v3.

> So, it makes perfect sense (or at least I thought it did) for holodoodler and dash-doodler to have toml files, CI, tests, and lists of dependencies. It also makes sense to lock the conda environments of those applications.

It also makes sense to me to test the applications and have these tests run in CI. I don't think I'll get there for HoloDoodler as it's quite time consuming. Locking the dependencies is critical though and I'll do that, otherwise if someone wants to use that project in a year it is likely it won't just work anymore. You're mentioning TOML files and I assume that means you thought about turning the applications into packages. This is indeed one way to distribute an application to users, making sure you lock the dependencies. One thing to be careful with when locking the dependencies with conda is that you may lock binary dependencies that are just available on one operating system. For HoloDoodler I plan to turn it into an [anaconda-project](https://anaconda-project.readthedocs.io/en/latest/), you can see how such projects look like on [examples.pyviz.org](https://github.com/pyviz-topics/examples/tree/master/carbon_flux), anaconda-project can generate lock files.

> The old 'yml' file in dash-doodler references python 3.6 is no longer used since the pydensecrf library was added to conda forge, as I explain https://github.com/Doodleverse/dash_doodler/issues/50.

Yes I've seen you're no longer Python 3.6 which is nice. This is why I have set `python_requires` to >=3.8 in this PR. 

> I guess I'm worried about declaring the requirements twice, once here, and again in each conda environment.

This is how it is usually done 🙃 Libraries declare their dependencies in a loose way, applications declare their dependencies in a fixed way.

> It makes me question what the purpose of the locked conda environment is at all.

The purpose of locking is really to make sure that your users are getting a functioning version of your application. Without locking they may install a new version of a package that breaks your application.

> It is my memory that we moved the doodler-engine to pip exactly to avoid having to declare dependencies twice, and it has worked well so far. My expectation was to lock the conda environments and this would be a done-deal.

I'm sorry there was confusion! In the end this is your project and this is just a PR, you're free not to accept it or amend it as you like, I won't mind at all :) Technically not declaring the dependencies of doodler_engine isn't wrong, it's just bizarre to my eyes and doesn't set you up really well for the future.

**Comment by ddbuscombe** [comment]
Thanks @maximlt , very clear. I guess the piece of information I was looking for was "Libraries declare their dependencies in a loose way, applications declare their dependencies in a fixed way."

I will go ahead and merge this PR and see how to set up an API token (new to me). I will work with @2320sharon to eventually create some more tests

Note that we're still working on HoloDoodler on a new fork (https://github.com/Doodleverse/holodoodler) that has implemented some small changes and we'll continue to work on it. If you create the anaconda-project and lock the dependencies for your original pyviz implementation, we'll be hopefully behind you in a couple of months :nerd_face: 

Thanks again

**Comment by ddbuscombe** [comment]
Okay, I thank you for the efforts here and detailed discussions. I am well aware of the issues you raise but have decided against merging this PR at this time

I understand the goal was to make it so one set of commands could install the entire package. However, since some of the dependencies are only installable via conda, it seems more fruitful to make a conda package and skip pip altogether.

This package is never intended to be installed into an empty conda env, only existing ones (separate for Dash- and Holo-doodlers). Not all the packages listed are available through pip

The requirements.txt file list pydensecrf as a dependency. The pip package for it has not been updated since 2018, so we can't install the latest version with pip and because of this limitation we have to use conda to install the latest version of the package. If we use this code in pyproject.toml that reads the requirements.txt file into the doodler engine's dependencies [tool.setuptools.dynamic]  dependencies = {file = ["requirements.txt"]} it will always fail to install the doodler_engine via pip because the pydensecrf pypi package is out of date. It is one of the major reasons why we adopted the workflow we have

@2320sharon suggests an alternative workflow. We can keep the `requirements.txt` file for users who want to install with conda and in the `pyproject.toml` file's dependencies, we can list all the pip installable dependencies. The downside is it does require users to run the command `conda install pydensecrf` in their environment , but it does allow for the pip and conda dependencies to all live in the same environment.

So we come back to the existing solution (which I admit is non-standard, but it works): we just tell the user to pip install the doodler-engine in their environment then install any conda-only dependencies like pydensecrf. This is exactly what the Dash- and Holo-doodler workflows are now. 

If we want to declare the dependencies for the pip package, we can list the pip installable packages in the `pyproject.toml`'s dependencies section and leave a section on the readme that tells the user to install the conda dependencies. But the latter is not necessary because we already have conda solutions that do this

In the readme we should declare this package is meant to serve two specific projects and that they need to run the following commands to install the dependencies manually. This package intentionally does not declare any dependencies, even though we are aware this is bad practice in software development. I've never been afraid to bend rules when I need to :wink: 

We are considering major changes to the code so we no longer have the headache of relying on `pydensecrf` in the future. So, these are still actively being developed and it doesnt make sense to package at this time

The demo `pyviz` holodoodler is now being worked on further (on our Doodleverse fork). Its dependencies are not set in stone; there will likely be further changes as we incorporate the ability to work with geotiffs and add necessary functionality like doodle editing

Again, I appreciate the hard work and fruitful discussion @maximlt

**Comment by maximlt** [comment]
Hi @dbuscombe-usgs!

> I am well aware of the issues you raise but have decided against merging this PR at this time

That's alright :)

Just a few comments:

- Happy to hear you have plans to get rid of `pydensecrf` as a dependency. Alternatively, if it's too hard to get rid of it, at this point forking it would be the best option, since its maintainer is clearly no longer paying attention to it.
- This PR wasn't only defining the runtime dependencies, it was setting up the CI for automatically deploying doodler_engine to PyPI and for running a potential test suite (by the way I encourage you to write a test suite for doodler_engine alone), and was updating how doodler_engine was being packaged. Feel free to re-use that if you like, to make it dependency-less I think you'd just have to remove this from `pyproject.toml`:

```
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies.dev]
file = ["requirements-dev.txt"]
```

I'm happy to see you're working on a fork of HoloDoodler. Don't hesitate to ping me there if you have any question. I guess it means that I could archive pyviz-topics/holodoodler (after locking the dependencies!).

**Pull request closed without merging**
